TortugaResearch/Tortuga.Chain

- Tortuga.Chain/Tortuga.Chain.Core.net461/Appenders/Appender.cs
- Tortuga.Chain/Tortuga.Chain.Core.net461/Appenders/Appender`1.cs
- Tortuga.Chain/Tortuga.Chain.Core.net461/ILink.cs
- Tortuga.Chain/Tortuga.Chain.Core.net461/ILink`1.cs
- Tortuga.Chain/Tortuga.Chain.Core.net461/Materializers/Materializer`3.cs
- Tortuga.Chain/Tortuga.Chain.Core.net461/Materializers/NonQueryMaterializer`2.cs
Let me know if this works to resolve #28 (SQL Materializer) in the issue tracker, or if we want to implement it differently.
> Added Sql method to ILink and various implementations.

- Tortuga.Chain/Tortuga.Chain.SqlServer.source/shared/SqlServer/SqlServerMetadataCache.cs
> 'isnullable' error on the sql server implementation

- Tortuga.Chain/Tests.Tortuga.Chain.SqlServer.source/Class2Databases/InsertBatchTests.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.source/shared/SqlServer/CommandBuilders/SqlServerInsertBatch.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.source/shared/SqlServer/SqlServerDataSourceBase.cs
> Changed API on InsertBatch to reduce user errors. #172

- Tortuga.Chain/Tortuga.Chain.Access.source/shared/AccessDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Core.source/shared/GenericDbDataSource.cs
- Tortuga.Chain/Tortuga.Chain.MySql.source/shared/MySqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql.source/shared/PostgreSqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SQLite.source/shared/SQLiteDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.source/shared/SqlServerDataSource.cs
> Make methods on IRootDataSource public #222

- .gitignore
- Tortuga.Chain/Tortuga.Chain.PostgreSql.source/Tortuga.Chain.PostgreSql.source.csproj
- Tortuga.Chain/Tortuga.Chain.PostgreSql.source/shared/PostgreSql/PostgreSqlMetadataCache.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql.source/shared/PostgreSql/PostgreSqlObjectName.cs
- Tortuga.Chain/xTests.Tortuga.Chain.PostgreSql.source/Custom/Setup.cs
- Tortuga.Chain/xTests.Tortuga.Chain.PostgreSql.source/Custom/TestBase.cs
- Tortuga.Chain/xTests.Tortuga.Chain.SqlServer.source/shared/Asserts/CollectionAsserts.cs
- Tortuga.Chain/xTests.Tortuga.Chain.SqlServer.source/shared/Asserts/Sdk/Exceptions/NotEmptyException.cs
- Tortuga.Chain/xTests.Tortuga.Chain.SqlServer.source/shared/Core/MetadataTests.cs
https://tortugatech.wordpress.com/2018/11/09/which-table-default-schema-in-postgresql-and-how-they-enable-multi-tenant-databases/
> Postgre sql default schema

- Tortuga.Chain/Tortuga.Chain.Access/Access/AccessOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Access/AccessDataSource.cs
- Tortuga.Chain/Tortuga.Chain.MySql/MySql/MySqlOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.MySql/MySqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/PostgreSql/PostgreSqlOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/PostgreSqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLite/SQLiteOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLiteDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/OleDbSqlServerDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/SqlServer/OleDbSqlServerOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServerDataSource.cs
WithUser should accept nulls #317
> WithUser should accept nulls #317

- Tortuga.Chain/Shared/Tests/CommandBuilders/FromTests.cs
- Tortuga.Chain/Shared/Tests/Core/AuditRulesTests.cs
- Tortuga.Chain/Tortuga.Chain.Core/CommandBuilders/IObjectDbCommandBuilder`1.cs
- Tortuga.Chain/Tortuga.Chain.Core/CommandBuilders/ISingleRowDbCommandBuilder.cs
- Tortuga.Chain/Tortuga.Chain.Core/CommandBuilders/ObjectDbCommandBuilder`3.cs
- Tortuga.Chain/Tortuga.Chain.Core/CommandBuilders/SingleRowDbCommandBuilder`2.cs
- Tortuga.Chain/Tortuga.Chain.Core/Materializers/SingleRow/ObjectOrNullMaterializer`3.cs
- Tortuga.Chain/Tortuga.Chain.Core/Materializers/SingleRow/RowMaterializer`2.cs
- Tortuga.Chain/Tortuga.Chain.Core/Tortuga.Chain.Core.xml
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS/Tortuga.Chain.SqlServer.MDS.xml
> Differentiate .ToObject and .ToObjectOrNull #323

- Tortuga.Chain/Tortuga.Chain.Core/UpdateOptions.cs
> UpdateOptions.IgnoreRowsAffected Documentation is Wrong #328

- Tortuga.Chain/Shared/Tests/CommandBuilders/FromTests.cs
- Tortuga.Chain/Tortuga.Chain.Core/CommandBuilders/SqlBuilder`1.cs
- Tortuga.Chain/Tortuga.Chain.Core/SortDirection.cs
- Tortuga.Chain/Tortuga.Chain.Core/SortExpression.cs
- Tortuga.Chain/Tortuga.Chain.Core/Tortuga.Chain.Core.xml
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS/Tortuga.Chain.SqlServer.MDS.xml
> SortExpression should be a struct, not a class #331

- Tortuga.Chain/Shared/Legacy/LegacyUtilities.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/PostgreSql/PostgreSqlMetadataCache.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/Tortuga.Chain.PostgreSql.csproj
PostgreSQL Server_Version Fails #355
> Tortuga.Chain.PostgreSql.3.2.1

- Tortuga.Chain/Shared/DataSource/DataSource.Common.cs
- Tortuga.Chain/Shared/DataSource/DataSource.IRootDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Access/AccessDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Core/DataSources/IRootDataSource.cs
- Tortuga.Chain/Tortuga.Chain.MySql/MySqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/PostgreSqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLiteDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/OleDbSqlServerDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServerDataSource.cs
> CreateOpenDataSource should have a no-parameter overload #354

- Tortuga.Chain/Shared/Tests/Core/AuditRulesTests.cs
- Tortuga.Chain/Tortuga.Chain.Access.Tests/TestBase.cs
- Tortuga.Chain/Tortuga.Chain.Core/AuditRules/SoftDeleteRule.cs
- Tortuga.Chain/Tortuga.Chain.MySql.Tests/TestBase.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql.Tests/TestBase.cs
- Tortuga.Chain/Tortuga.Chain.SQLite.Tests/TestBase.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS.Tests/TestBase.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb.Tests/TestBase.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.Tests/TestBase.cs
> Missing default for soft delete rule 357

- Tortuga.Chain/Shared/Tests/CommandBuilders/FromTests.cs
- Tortuga.Chain/Shared/Tests/CommandBuilders/TableFunctionTests.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS/Tortuga.Chain.SqlServer.MDS.csproj
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/CommandBuilders/ISupportsApproximateCount.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/CommandBuilders/SqlServerTableFunction.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/CommandBuilders/SqlServerTableOrView.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerAppenders.cs
> Approximate distinct count in SQL Server 

- Tortuga.Chain/Shared/DataSource/DataSourceBase.Class1DataSource.cs
- Tortuga.Chain/Shared/Tests/CommandBuilders/FromTests.cs
- Tortuga.Chain/Tortuga.Chain.Access/Access/AccessDataSourceBase.CommandBuilders.cs
- Tortuga.Chain/Tortuga.Chain.Core/CommandBuilders/MultipleRowDbCommandBuilder`3.cs
- Tortuga.Chain/Tortuga.Chain.MySql/MySql/MySqlDataSourceBase.CommandBuilders.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/PostgreSql/PostgreSqlDataSourceBase.CommandBuilders.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLite/SQLiteDataSourceBase.CommandBuilders.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/SqlServer/OleDbSqlServerDataSourceBase.CommandBuilders.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerDataSourceBase.CommandBuilders.cs
> Rework GetByKeyList to not require a table name

- Tortuga.Chain/Shared/Tests/Appenders/SqlDependencyTests.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS.Tests/Tortuga.Chain.SqlServer.MDS.Tests.csproj
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS/Tortuga.Chain.SqlServer.MDS.csproj
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/Appenders/NotifyChangeAppender`1.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/CommandBuilders/ISupportsChangeListener.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/CommandBuilders/SqlServerProcedureCall.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/CommandBuilders/SqlServerSqlCall.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/CommandBuilders/SqlServerTableOrView.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/Materializers/WaitForChangeMaterializer.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/Materializers/WaitForChangeMaterializer`1.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerAppenders.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerCommandExecutionToken.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServerDataSource.cs
This removed a bunch of `#if` statements that are no longer needed since Microsoft fixed their bug.
> Enabled SQL Dependency in Tortuga.Chain.SqlServer.MDS #327

- Tortuga.Chain/Tortuga.Chain.Access/Tortuga.Chain.Access.csproj
- Tortuga.Chain/Tortuga.Chain.CompiledMaterializers/Tortuga.Chain.CompiledMaterializers.csproj
- Tortuga.Chain/Tortuga.Chain.Core.Odbc/Tortuga.Chain.Core.Odbc.csproj
- Tortuga.Chain/Tortuga.Chain.Core.OleDb/Tortuga.Chain.Core.OleDb.csproj
- Tortuga.Chain/Tortuga.Chain.Core/Tortuga.Chain.Core.csproj
- Tortuga.Chain/Tortuga.Chain.MySql/Tortuga.Chain.MySql.csproj
- Tortuga.Chain/Tortuga.Chain.PostgreSql/Tortuga.Chain.PostgreSql.csproj
- Tortuga.Chain/Tortuga.Chain.SQLite/Tortuga.Chain.SQLite.csproj
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS/Tortuga.Chain.SqlServer.MDS.csproj
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/Tortuga.Chain.SqlServer.OleDb.csproj
- Tortuga.Chain/Tortuga.Chain.SqlServer/Tortuga.Chain.SqlServer.csproj
Hide dependency on source generator
> Cleanup NuGet package code.

- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServerDataSource.cs
> Sql server data source.begin transaction 461

- Tortuga.Chain/Shared/DataSource/CommandBuilders/SupportsGetByKeyListTrait`4.cs
- Tortuga.Chain/Tortuga.Chain.Access/Generated/Tortuga.Shipwright/Tortuga.Shipwright.TraitGenerator/Tortuga.Chain.Access.AccessDataSourceBase.cs
- Tortuga.Chain/Tortuga.Chain.Core/DataSources/ISupportsGetByKey.cs
- Tortuga.Chain/Tortuga.Chain.Core/DataSources/ISupportsGetByKeyList.cs
- Tortuga.Chain/Tortuga.Chain.MySql/Generated/Tortuga.Shipwright/Tortuga.Shipwright.TraitGenerator/Tortuga.Chain.MySql.MySqlDataSourceBase.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/Generated/Tortuga.Shipwright/Tortuga.Shipwright.TraitGenerator/Tortuga.Chain.PostgreSql.PostgreSqlDataSourceBase.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/Generated/Tortuga.Shipwright/Tortuga.Shipwright.TraitGenerator/Tortuga.Chain.SQLite.SQLiteDataSourceBase.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS/Generated/Tortuga.Shipwright/Tortuga.Shipwright.TraitGenerator/Tortuga.Chain.SqlServer.SqlServerDataSourceBase.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/Generated/Tortuga.Shipwright/Tortuga.Shipwright.TraitGenerator/Tortuga.Chain.SqlServer.OleDbSqlServerDataSourceBase.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/Generated/Tortuga.Shipwright/Tortuga.Shipwright.TraitGenerator/Tortuga.Chain.SqlServer.SqlServerDataSourceBase.cs
> Get by key update by key and delete by key should support system.int16 443

- Tortuga.Chain/Shared/Tests/Appenders/CommandTimeoutTests.cs
- Tortuga.Chain/Shared/Tests/Appenders/SqlDependencyTests.cs
- Tortuga.Chain/Tortuga.Chain.Access/Access/AccessOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Access/Access/AccessTransactionalDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Access/AccessDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Core/Core/CommandExecutionToken`2.cs
- Tortuga.Chain/Tortuga.Chain.Core/GenericDbDataSource.cs
- Tortuga.Chain/Tortuga.Chain.MySql/MySqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/PostgreSqlDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLite/SQLiteOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLite/SQLiteTransactionalDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLiteDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/OleDbSqlServerDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerDataSourceBase.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerOpenDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerTransactionalDataSource.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServerDataSource.cs
> Sql command.enable optimized parameter binding 439

- Tortuga.Chain/Shared/DataSource/OpenDataSourceTrait`5.cs
- Tortuga.Chain/Shared/DataSource/RootDataSourceTrait`7.cs
- Tortuga.Chain/Shared/DataSource/TransactionalDataSourceTrait`5.cs
- Tortuga.Chain/Tortuga.Chain.Core/Core/CacheClearedEventArgs.cs
- Tortuga.Chain/Tortuga.Chain.Core/Core/CacheInvalidatedEventArgs.cs
- Tortuga.Chain/Tortuga.Chain.Core/Core/CacheReadEventArgs.cs
- Tortuga.Chain/Tortuga.Chain.Core/Core/CacheWrittenEventArgs.cs
- Tortuga.Chain/Tortuga.Chain.Core/Core/ICacheAdapter.cs
- Tortuga.Chain/Tortuga.Chain.Core/Core/ObjectCacheAdapter.cs
- Tortuga.Chain/Tortuga.Chain.Core/DataSources/DataSource.cs
- Tortuga.Chain/Tortuga.Chain.Core/DataSources/IDataSource.cs
- Tortuga.Chain/Tortuga.Chain.Core/GenericDbDataSource.cs
> Add events to ICacheAdapter #190

- Tortuga.Chain/Changelog.md
- Tortuga.Chain/Tortuga.Chain.Core/ListOptions.cs
- Tortuga.Chain/Tortuga.Chain.Core/Materializers/SingleColumn/CollectionColumnMaterializer`4.cs
- Tortuga.Chain/Tortuga.Chain.Core/Materializers/SingleColumn/SingleColumnMaterializer`3.cs
> Improve column name support for list based materializers 24

- Tortuga.Chain/Tortuga.Chain.Access/Access/AccessDataSourceBase.Traits.cs
- Tortuga.Chain/Tortuga.Chain.Access/Access/CommandBuilders/AccessInsertObject`1.cs
- Tortuga.Chain/Tortuga.Chain.Access/Access/Utilities.cs
- Tortuga.Chain/Tortuga.Chain.MySql/MySql/MySqlDataSourceBase.Traits.cs
- Tortuga.Chain/Tortuga.Chain.MySql/MySql/Utilities.cs
- Tortuga.Chain/Tortuga.Chain.PostgreSql/PostgreSql/Utilities.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLite/SQLiteDataSourceBase.Traits.cs
- Tortuga.Chain/Tortuga.Chain.SQLite/SQLite/Utilities.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/SqlServer/OleDbSqlServerDataSourceBase.Traits.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.OleDb/SqlServer/Utilities.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/SqlServerDataSourceBase.Traits.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer/shared/SqlServer/Utilities.cs
Fixed the bug where we were not detecting the length of string parameters.
> Parameter lengths #499

- Tortuga.Chain/Changelog.md
- Tortuga.Chain/Shared/Tests/Appenders/TagTests.cs
- Tortuga.Chain/Tortuga.Chain.Core/Appenders/TagAppender`1.cs
- Tortuga.Chain/Tortuga.Chain.Core/CommonAppenders.cs
> Tag queries #401

- Tortuga.Chain/Shared/Tests/Appenders/SqlServerHintTests.cs
- Tortuga.Chain/Tortuga.Chain.SqlServer.MDS/SqlServer/SqlServerAppenders.cs
Add TObject support to the WithIndex and WithIsolationLevel calls.
> Add TObject support to the WithIndex and WithIsolationLevel calls.
